### DISCUSSION TITLE
.qmd rendering issue

### DISCUSSION THREAD

**Discussion by kinmic** [pfmc-assessments/Assessment_Class#91] [General]
Hi all,

Can anyone provide any insight on the error below
```
==> quarto preview SAR_PFMC_skeleton.qmd --to pdf --no-watch-inputs --no-browse



processing file: SAR_PFMC_skeleton.qmd
                                                                                                                     
output file: SAR_PFMC_skeleton.knit.md

There were 14 warnings (use warnings() to see them)
WARNING: Warning: diff of engine output timed out. No source lines will be available.
pandoc 
  to: latex
  output-file: SAR_PFMC_skeleton.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999997 (TeX Live 2025) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Undefined control sequence.
<argument> \acrlong 
                    {s-tri}
l.1819 ...ring{\acrlong{s-tri}}{}}\label{section}}
                                                  
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

 

see SAR_PFMC_skeleton.log for more information.
```

The reports seem be endering finding on other computers, however Will Patrone and I are getting this error. So far I've tried:
- Removing all other latex dists (MikTex)
- Uninstalling and reinstalling tiny tex as per the sa4ss installation instructions.
- Ensuring the correct version of R and Rscripts are available in my path.
- Ensuring that the tinytex executable (e.g pdflatex.exe) are available in my path.
- Adding latex glossaries package directly to the YAML and or to the .tex files

No-one running a Mac has had these issues, and laurie is having no problem rendering on windows.

Any advice on how to fix this? Anything I can find online is telling me to add additional packages to the .tex iles or to the YAML, but given that these files are working fine om other PC's this feels like its probably not the issue?

**Comment by mcgoodman** [comment]
The `\acrlong` control sequence is seemingly only used in three headings in the `data.qmd` file - does it render if you replace those heading with plain text, e.g. `### \acrlong{s-tri}` --> `### Alaska Fisheries Science Center/Northwest Fisheries Science Center West Coast Triennial Shelf Survey`?

**Reply by kinmic** [reply]
Gave that  whirl but it then fails at \gls {s-wcgbt} . Its like it just isn't reading the sa4ss_glossaries.tex at all.

```
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999997 (TeX Live 2025) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Undefined control sequence.
l.1840 Trawl Survey (\gls
                         {s-wcgbt}) has been conducted annually, since 2003. It
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

 

see SAR_PFMC_skeleton.log for more information.
```

**Comment by gertsevv** [comment]
@okenk and @iantaylor-NOAA - do you have any advice on that?

**Reply by okenk** [reply]
The error looks like it is because it isn’t recognizing commands from the glossary package, not the list of acronyms. That package gets loaded in the PFMC.tex file. Does that file exist and is it loaded in the skeleton YAML?

**Reply by kinmic** [reply]
Yep pfcm.tex exists and is included in the yaml 

```
date: today
lang: en
keep-tex: true
cover:
pdf-engine: lualatex
format:
  pdf:
    documentclass: scrartcl
    toc: true
    number-sections: true
    template-partials:
      - 'support_files/before-body.tex'
      - 'support_files/_titlepage.tex'
    include-in-header:
      - 'support_files/in-header.tex'
      - 'support_files/pfmc.tex'
      - text: '\lohead{Widow Rockfish assessment 2025}'
    lof: false
    lot: false
    titlepage-geometry:
      - top=2in
      - bottom=1in
      - right=1in
      - left=1in
    fig-pos: 'H'
    reference-location: section
output-file: 'WIDOW_SAR_2025'
params:
  office: 'NWFSC'
  species: 'Widow Rockfish'
  spp_latin: 'Sebastes entomelas'
  region: 'U.S. West Coast'
bibliography:
  - asar_references.bib
csl: 'canadian-journal-of-fisheries-and-aquatic-sciences.csl'
---

```
